Use TraoDoiDoCu
GO
ALTER TABLE Users
ADD BanDate Datetime
GO
ALTER TABLE Users
ADD BanTime int
GO
CREATE TABLE [dbo].[GlobalDatas](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[Content] [nvarchar](255) NULL,
 CONSTRAINT [PK_GlobalDatas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
