//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDoCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Comment = new HashSet<Comment>();
            this.FollowProduct = new HashSet<FollowProduct>();
            this.ProductImage = new HashSet<ProductImage>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Location { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<FollowProduct> FollowProduct { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
    }
}
